# Compiler and flags

CC=g++
CCFLAGS=-O2 -pipe -pthread -fpermissive
INCLUDE=-I .

# Utilities

MKDIR_P=mkdir -p

# Directories

BIN=bin
TEST=test
SRC=src
SCRIPTS=scripts


SRC_AI=$(SRC)/ai
SRC_COM=$(SRC)/communications
SRC_DATA=$(SRC)/data

SRC_SERVER=$(SRC)/server
SRC_CLIENTS=$(SRC)/clients
SRC_CLIENT_TERMINAL=$(SRC_CLIENTS)/terminal
SRC_CLIENT_GRAPHICS=$(SRC_CLIENTS)/graphics


BIN_AI=$(BIN)/ai
BIN_COM=$(BIN)/communications
BIN_DATA=$(BIN)/data

BIN_SERVER=$(BIN)/server
BIN_CLIENTS=$(BIN)/clients
BIN_CLIENT_TERMINAL=$(BIN_CLIENTS)/terminal
BIN_CLIENT_GRAPHICS=$(BIN_CLIENTS)/graphics

TARGET_SERVER=$(BIN)/Server
TARGET_CLIENT_TERMINAL=$(BIN)/Client_terminal
TARGET_CLIENT_GRAPHICS=$(BIN)/Client_graphics

# Files

AI_HEADERS=$(wildcard $(SRC_AI)/*.h)
AI_SOURCES=$(patsubst $(SRC_AI)/%.h,$(SRC_AI)/%.cpp,$(AI_HEADERS))
AI_BINAIRIES=$(patsubst $(SRC_AI)/%.h,$(BIN_AI)/%.o,$(AI_HEADERS))

COM_HEADERS=$(wildcard $(SRC_COM)/*.h)
COM_SOURCES=$(patsubst $(SRC_COM)/%.h,$(SRC_COM)/%.cpp,$(COM_HEADERS))
COM_BINAIRIES=$(patsubst $(SRC_COM)/%.h,$(BIN_COM)/%.o,$(COM_HEADERS))

DATA_HEADERS=$(wildcard $(SRC_DATA)/*.h)
DATA_SOURCES=$(patsubst $(SRC_DATA)/%.h,$(SRC_DATA)/%.cpp,$(DATA_HEADERS))
DATA_BINAIRIES=$(patsubst $(SRC_DATA)/%.h,$(BIN_DATA)/%.o,$(DATA_HEADERS))

SERVER_HEADERS=$(wildcard $(SRC_SERVER)/*.h)
SERVER_SOURCES=$(patsubst $(SRC_SERVER)/%.h,$(SRC_SERVER)/%.cpp,$(SERVER_HEADERS))
SERVER_BINAIRIES=$(patsubst $(SRC_SERVER)/%.h,$(BIN_SERVER)/%.o,$(SERVER_HEADERS))

CLIENT_TERMINAL_HEADERS=$(wildcard $(SRC_CLIENT_TERMINAL)/*.h)
CLIENT_TERMINAL_SOURCES=$(patsubst $(SRC_CLIENT_TERMINAL)/%.h,$(SRC_CLIENT_TERMINAL)/%.cpp,$(CLIENT_TERMINAL_HEADERS))
CLIENT_TERMINAL_BINAIRIES=$(patsubst $(SRC_CLIENT_TERMINAL)/%.h,$(BIN_CLIENT_TERMINAL)/%.o,$(CLIENT_TERMINAL_HEADERS))

CLIENT_GRAPHICS_HEADERS=$(wildcard $(SRC_CLIENT_GRAPHICS)/*.h)
CLIENT_GRAPHICS_SOURCES=$(patsubst $(SRC_CLIENT_GRAPHICS)/%.h,$(SRC_CLIENT_GRAPHICS)/%.cpp,$(CLIENT_GRAPHICS_HEADERS))
CLIENT_GRAPHICS_BINAIRIES=$(patsubst $(SRC_CLIENT_GRAPHICS)/%.h,$(BIN_CLIENT_GRAPHICS)/%.o,$(CLIENT_GRAPHICS_HEADERS))

# Rules

all: dirs $(AI_BINAIRIES) $(COM_BINAIRIES) $(DATA_BINAIRIES) $(SERVER_BINAIRIES) \
		 $(CLIENTS_TERMINAL_BINAIRIES) $(CLIENTS_GRAPHICS_BINAIRIES) $(TARGET_SERVER) $(TARGET_CLIENT_TERMINAL) $(TARGET_CLIENT_GRAPHICS)

dirs:
	$(MKDIR_P) $(BIN) $(BIN_AI) $(BIN_COM) $(BIN_DATA) $(BIN_SERVER) $(BIN_CLIENTS) $(BIN_CLIENT_GRAPHICS) $(BIN_CLIENT_TERMINAL)

$(BIN)/%.o: $(SRC)/%.cpp
	$(CC) $(CCFLAGS) $(INCLUDE) -c $< -o $@

$(TARGET_SERVER): $(AI_BINAIRIES) $(COM_BINAIRIES) $(DATA_BINAIRIES) $(SERVER_BINAIRIES)
	$(CC) $(CCFLAGS) $(INCLUDE) $^ -o $@

$(TARGET_CLIENT_TERMINAL): $(AI_BINAIRIES) $(COM_BINAIRIES) $(DATA_BINAIRIES) $(CLIENT_TERMINAL_BINAIRIES)
	$(CC) $(CCFLAGS) $(INCLUDE) $^ -o $@

$(TARGET_CLIENT_GRAPHICS): $(AI_BINAIRIES) $(COM_BINAIRIES) $(DATA_BINAIRIES) $(CLIENT_TERMINAL_GRAPHICS)
	$(CC) $(CCFLAGS) $(INCLUDE) $^ -o $@

clean:
	rm -rf $(BIN)
